version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_admin
      MYSQL_PASSWORD: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_admin
      WORDPRESS_DB_PASSWORD: /run/secrets/db_password
    secrets:
      - db_password

secrets: 
  db_password:
    file: /var/secret/db_password.txt
  db_root_password:
    file: /var/secret/db_root_pasword.txt

volumes:
  db_data: {}
  wordpress_data: {}