all:
  hosts:
  children:
    servers:
      hosts:
        10.0.5.5:
          hostname: Blue9-DC
        
        10.0.5.6:
          hostname: Blue9-FS
      vars:
        domain_ou_path: "OU=Servers,OU=Computers,OU=blue9,DC=blue9,DC=local"
        ansible_shell_type: powershell
        accounts_ou: "OU=Accounts,OU=Blue9,DC=blue9,DC=local"
        groups_ou: "OU=Groups,OU=Accounts,OU=blue9,DC=blue9,DC=local"
        ansible_user: Administrator@BLUE9.LOCAL
    workstation:
      hosts:
        10.0.5.85:
          hostname: Blue9-wks1
        
        10.0.5.86:
          hostname: Blue9-wks2
      vars:
        domain_ou_path: "OU=Workstations,OU=Computers,OU=blue9,DC=blue9,DC=local"
        ansible_shell_type: powershell
  vars:
    ansible_user: deployer
    device: Ethernet0
    netmask: 255.255.255.0
    gateway: 10.0.5.2
    name_server: 10.0.5.5
    domain: blue9.local
    