# Playbook to create group sepcific file shares. 
- name: Create shares
  hosts: 10.0.5.6
  tasks:

  - name: Install File System
    win_feature:
      name: File-Services
      state: present
      include_sub_features: yes
    register: win_feature 

  - name: Create Share
    win_share:
      name: Test
      description: test
      path: C:\shares\test
      list: yes
      full: Administrators