---
- name: domain joiner
  hosts: windows
  gather_facts: no
  vars_prompt:
  - name: Admin-acc
    prompt: "What is the admin account name? (Include the @blue9.local)"
    private: yes
  
  - name: Admin-pass
    prompt: "What is the admin password?"
    private: yes

  tasks:
  - win_domain_membership:
      dns_domain_name: "{{ domain }}"
      hostname: "{{ hostname }}"
      domain_admin_user: "Administrator@blue9.local"
      domain_admin_password: "{{ Admin-pass }}"
      domain_ou_path: "{{ domain_ou_path }}"
      state: domain
    register: domain-state

  - ansible.windows.win_reboot:
    when: domain_state.reboot_required
      