#This Playbook parses a csv file to create AD users
- name: AD Users Creation
  hosts: 10.0.5.5
  tasks:
  
  - name: read group_file
    command: cat ../files/groups.txt
    register: groupnames
    delegate_to: 127.0.0.1

  - name: Create Groups
    win_domain_group:
      name: "{{ item }}"
      scope: domainlocal
      category: security
      organizational_unit: "{{ groups_ou }}"
      ignore_protection: yes
    with_items: "{{groupnames.stdout_lines}}"
 
  - name: read_csv
    read_csv:
      path: ../files/accounts.csv
    register: accounts
    delegate_to: 127.0.0.1

#  - name: loop
#    debug:
#      msg: "{{ item.account_name }} - {{ item.group }}"
#    with_items: "{{ accounts.list }}"
