#This Playbook parses a csv file to create AD users
- name: AD Users Creation
  hosts: 10.0.5.5
  vars_prompt:
  - name: acc
    prompt: "What is the new admin account name?"
    private: no
  
  - name: pass
    prompt: "What is the new admin password?"
    private: yes
  tasks:
  - name: add new domain admin
    win_domain_user:
      name: '{{ acc }}'
      password: '{{ pass }}'
      state: present
      groups:
        - Domain Admins

  - name: read group_file
    command: cat ../files/groups.txt
    register: groupnames
    delegate_to: 127.0.0.1

  - name: Create Groups
    win_domain_group:
      name: "{{ item }}"
      scope: domainlocal
      category: security
      organizational_unit: "{{ groups_ou }}"
      ignore_protection: yes
    with_items: "{{groupnames.stdout_lines}}"
 
  - name: read_csv
    read_csv:
      path: ../files/accounts.csv
    register: accounts
    delegate_to: 127.0.0.1
  
  - name: Create Users
    win_domain_user:
      name: "{{ item.account_name }}"
      firstname: "{{ item.name }}"
      password: "{{ item.password }}"
      groups:
        - "{{ item.group }}"
      path: "{{ accounts_ou }}"
    with_items: "{{ accounts.list }}"
