---
- name: windows remote access
  hosts: workstation
  gather_facts: no
  tasks: 
  - name: change Power Plan
    community.windows.win_power_plan:
      name: high performance

  - name: Add members to RDP
    win_group_membership:
      name: Remote Desktop Users
      members: Blue9\Domain Admins
      state: present

  - name: Enable RDP
    win_shell: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
    
  - name: Edit Firewall
    win_shell: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
