## Centos Congif written by Sam Johnson with guidance from Devan Paden.
- name: centos config
  hosts: wordpress
  tasks: 
  - name: Create the .ssh directory if it is not there
    file: 
      path: "/home/{{ ansible_user}}/.ssh"
      state: directory
      mode: 0700
  - name: create authorized_keys file
    file: 
      path: "/home/{{ ansible_user }}/.ssh/authorized_keys"
      state: touch
      mode: 0644
  - name: copy over key block and append to auth keys
    blockinfile: 
      dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
      block: "{{ public_key }}"

  - name: create sudoers dropin file for 480
    file: 
      path: /etc/sudoers.d/480
      state: touch
      mode: 0440
    become: yes 

  - name: create a drop in entry in /etc/sudoers.d/480
    blockinfile: 
      dest: /etc/sudoers.d/480
      block: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    become: yes

  - name: set the hostname
    hostname: 
      name: "{{hostname}}"
    become: yes

  - name: add host to hosts file
    lineinfile: 
      path: /etc/hosts
      line: '127.0.1.1  {{ hostname }}'
    become: yes

  - name: push over the networking script
    template: 
      src: ../files/ifcfg.j2
      dest: '/etc/sysconfig/network-scripts/ifcfg-{{device}}'
      mode: 0644
      owner: root
      group: root
      force: yes
    become: yes

## Docker config based on script written by Sahil Suri in Linux Juggernaut, as well as commands from my previous install of Docker.  
- name: docker config
  hosts: wordpress
  become: yes
  tasks:
  - name: Upgrade
    yum:
      name: "*"
      state: latest
  - name: Install Prereqs
    yum:
      name:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - python-docker
      state: latest
  - name: Add Docker REPO
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
  - name: Install Docker
    yum: 
      name: docker
      state: latest
  - name: Start Docker
    service: 
      name=docker
      state=started
      enabled=yes
  - name: Install Docker Compose
    get_url: 
      url: https://github.com/docker/compose/releases/download/v2.1.0/docker-compose-linux-x86_64
      dest: /usr/local/bin/docker-compose"
      mode: +x
    
- name: Create secrets
  hosts: wordpress
  become: yes
  tasks:
  - name: Create secret path
    file:
      path: "/var/secret/"
      state: directory
      mode: 0700
  - name: Create secret file 1
    file:
      path: "/var/secret/db_password.txt"
      state: touch
      mode: 0644
  - name: Create secret file 2
    file:
      path: "/var/secret/db_root_password.txt"
      state: touch
      mode: 0644
  - name: Copy over secret 1
    blockinfile:
      dest: "/var/secret/db_password.txt"
      block: "{{ wp_rp }}"
  - name: Copy over secret 1
    blockinfile:
      dest: "/var/secret/db_password.txt"
      block: "{{ wp_dp }}"

- name: Pull Docker File from Github
  hosts: wordpress
  tasks: 
  - name: Pull file from Github
    get_url: 
      url: https://github.com/ArtTHEbard/SYS480/blob/main/ansible/files/wordpress.yml
      dest: /home/{{ansible_user}}/wordpress.yml

- name: Run Docker File
  hosts: wordpress
  become: yes
  tasks:
  - name: deploy Docker File
    docker_compose:
      project_src: /home/{{ ansible_user}}/
      files:
      - wordpress.yml
    

- name: bounce the network
  hosts: wordpress
  tasks:
  - name: Bounce Network
    shell: "sleep 5 && systemctl restart network"
    async: 1
    poll: 0
  become: yes